site_name: Bases de Datos NoSQL

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    #- navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - toc.integrate
    - navigation.footer
    - navigation.path
    
  copyright: Licenciado bajo la licencia Creative Commons by-nc-nd

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro

extra_css:
  - css/extra.css

markdown_extensions:
  - admonition
  - tables    
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
 
  - MONGODB:
    - 1 - MongoDB: 1__mongodb.md
    - 2 - Estructura JSON: 2__estructura_json.md
    - 3 - Instalación:
        - 3.1 En Linux: 3.1__Linux.md
        - 3.2 En Windows: 3.2__Windows.md
        - 3.3 Con Docker: 3.3__Docker.md 
    - 4 - Funcionamiento: 4__funcionamiento.md
    - 5 - Variables: 5__variables.md
    - 6 - Tipos de datos: 6__tipo_datos.md
    - 7 - Operaciones CRUD: 7__crud.md
    - 8 - Operadores:
        - 8.1 Actualización: 8.1__operadores_actualizacion.md
        - 8.2 Consulta: 8.2__operadores_consulta.md
        - 8.3 📚 Ejercicios: 8.3__operadores_ejercicios.md
        - 8.4 Arrays: 8.4__Arrays.md
    - 9 - Agregación: 9__agregacion.md
    - 10 - Relaciones: 10__relaciones_mongo.md
    - 11 - Resumen Comandos: 11__resumen.md
  #- Ejercicios MongoDB: exercicis_mongo.md
  #- Práctica: 13__actividad_mongo.md
   
  #- BBDD NoSQL: 1__introducci.md
  #- Introducción: 1__introducci.md:
  
 # - REDIS:
    #- Introducción: 2__bases_de_dades_clauvalor.md
  #- Ejercicios Redis: exercicis_redis.md